version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - php74
      - mysql
      - redis

  php:
    image: php:fpm
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

  php74:
    image: php:7.4.33-fpm
    container_name: php74
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webroot
      MYSQL_USER: kejilion
      MYSQL_PASSWORD: kejilionYYDS

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data

  xui:
    image: enwaiax/x-ui:latest
    container_name: xui
    restart: always
    network_mode: host
    volumes:
      - ./db:/etc/x-ui # 数据库文件目录
      - ./cert:/root/cert #证书目录
      
