version: "3.9"
services:
  xui:
    image: enwaiax/x-ui
    container_name: xui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/.acme.sh/ui.cszc.link_ecc/
    restart: unless-stopped
    network_mode: host  


