version: "3.9"
services:
  xui:
    image: enwaiax/x-ui:latest
    container_name: xui
    restart: always
    network_mode: host
    volumes:
      - ./db:/etc/x-ui # 数据库文件目录
      - ./certs:/root/cert # 证书文件目录


